services:
  api:
    build: ./api
    expose:
      - "3000"
  proxy:
    # image: nginx:latest
    build:
      context: ./proxy/
      args:
        ENABLED_MODULES: brotli subs-filter
    image: custom-nginx:v1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/prod/config/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./proxy/prod/html/:/var/www/sites/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    # docker compose run --rm certbot renew

