services:
  api:
    build: ./api
    expose:
      - "3000"
  proxy:
    build:
      context: ./proxy/
      args:
        ENABLED_MODULES: brotli subs-filter ndk lua
    image: custom-nginx:v1
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/dev/config/:/etc/nginx/conf.d/:ro
      - ./proxy/dev/html/:/var/www/sites/:ro
      - ./proxy/dev/certs/:/etc/ssl/:ro
