#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "postgres"  <<-EOSQL
  BEGIN;
    CREATE USER $API_PGUSER WITH PASSWORD '$API_PGPASSWORD';
    ALTER USER $API_PGUSER CREATEDB;
  COMMIT;
EOSQL



